version: 2.1

.test_python_steps: &test_python_steps
  - checkout
  - run: sudo pip install -r requirements.txt "tox==3.24.*"
  - run: tox

jobs:
  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt "pylint==2.4.*" "ansible==2.9.*"
      - run: pylint filter_plugins
  test_python_3_8:
    docker:
      - image: circleci/python:3.8
    steps: *test_python_steps
  test_python_3_9:
    docker:
      - image: circleci/python:3.9
    steps: *test_python_steps
  test_python_3_10:
    docker:
      - image: circleci/python:3.10
    steps: *test_python_steps
  # If this step is failing you need to update README. Check out README.md for instructions.
  validate_readme:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt "ansible==2.9.*"
      - run: python apply_docstring_to_readme.py < README.md > /tmp/NEW_README.md
      - run: diff /tmp/NEW_README.md README.md
workflows:
  main:
    jobs:
      - lint
      - test_python_3_8
      - test_python_3_9
      - test_python_3_10
      - validate_readme
