version: 2.1

.test_python_steps: &test_python_steps
  - checkout
  - run: sudo pip install -r requirements.txt "tox==4.2.*"
  - run: tox

jobs:
  lint:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt "pylint==2.15.*" "ansible==7.1.*"
      - run: pylint filter_plugins
  test_python_3_8:
    docker:
      - image: circleci/python:3.8
    steps: *test_python_steps
    environment:
      # Ansible 7.* doesn't support python<3.9
      TOX_SKIP_ENV: py3-ansible71
  test_python_3_9:
    docker:
      - image: circleci/python:3.9
    steps: *test_python_steps
  test_python_3_10:
    docker:
      - image: circleci/python:3.10
    steps: *test_python_steps
  # If this step is failing you need to update README. Check out README.md for instructions.
  validate_readme:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Yes, we really need `ansible` in this job in order to correctly import xml module
      - run: sudo pip install -r requirements.txt  "ansible==7.1.*"
      - run: python apply_docstring_to_readme.py < README.md > /tmp/NEW_README.md
      - run: diff /tmp/NEW_README.md README.md
workflows:
  main:
    jobs:
      - lint
      - test_python_3_8
      - test_python_3_9
      - test_python_3_10
      - validate_readme
